.eslintignore, .eslintrc.js, .prettierignore, .prettierrc, package-lock.json, package.json, src/App.tsx, src/components/Layout/Layout.tsx, src/index.tsx, src/routes/Router.tsx, src/service/auth.ts
- merge 요청자: 없음
- eslint, prettier를 설정함
- eslint, prettier를 설정함
=> [240611] prettier, eslint 설정

package-lock.json, package.json, src/App.tsx, src/components/Header/Header.tsx, src/components/Layout/Layout.tsx, src/components/Layout/layout.module.css, src/components/Navbar/Navbar.tsx, src/components/icons/ArrowBackIcon.tsx, src/components/icons/CloseIcon.tsx, src/components/icons/CommentIcon.tsx, src/components/icons/HouseIcon.tsx, src/components/icons/UserIcon.tsx, src/pages/WriteReview/WriteReview.tsx, src/routes/Router.tsx
- merge 요청자: 없음
- 공통적인 header, navbar를 구현하여 추가하고자 함
- Header의 뒤로가기 버튼 구현
- Header의 닫기 버튼과 Navbar의 링크들은 아직 url이 미정되어 구현하지 않음
=>  [240611] SLOPE-29 header, navbar 구현

src/App.tsx, src/components/ui/Button.tsx, src/components/ui/Container.tsx, src/components/ui/Input.tsx, src/pages/Main/Main.tsx, src/pages/WriteReview/WriteReview.tsx
- merge 요청자: @
- 공통적으로 사용되는 버튼과 인풋 컴포넌트를 구현하였으므로 공유하고자 함
- Button, Input을 구현했으며 pages/WriteReview/WriteReview.tsx 에서 사용 예시를 확인할 수 있음
- http://localhost:3000/review/new 에서 구현된 것을 확인할 수 있음
=> [240611] 공통 컴포넌트 버튼, 인풋 구현

public/index.html, src/components/Map/CurrentMarker.tsx, src/components/Map/Map.tsx, src/components/Navbar/Navbar.tsx, src/global.d.ts, src/hooks/geoLocation.ts, src/index.tsx, src/pages/Main/Main.tsx
- merge 요청자: @
- map api를 연결하고 현재 위치 마커를 구현하여 공유하고자 함
- map api를 연결하고 현재 위치 마커를 구현함
=> [240611] map api 연결 및 현재 위치 구현

src/components/ui/Input.tsx
- merge 요청자: @
- Input 컴포넌트 width 변경 안 되는 문제 해결함
- html tag의 style 속성으로 width 변수를 사용함
=> [240613] Input 컴포넌트 width 변경 안 되는 문제 해결 

src/App.tsx, src/components/Header/Header.tsx, src/components/Navbar/FacilityOrRoadModal.tsx, src/components/Navbar/Navbar.tsx, src/components/icons/CloseIcon.tsx, src/components/ui/Modal.tsx, src/components/ui/ModalPortal.tsx
- merge 요청자: @
- 하단 제보 클릭시 시설, 도로를 선택할 수 있는 모달을 구현함
- 하단바의 '가게 제보'를 '제보'로 수정함
- 하단 제보 클릭시 시설, 도로를 선택할 수 있는 모달 구현
- 그 외에 공통적으로 활용할 수 있는 modal portal과 modal 구현
=> [240613] 시설 / 도로 선택 모달 구현

.env, src/App.tsx, src/components/Header/Header.tsx, src/components/Map/CenterMarker.tsx, src/components/Map/Map.tsx, src/components/Navbar/Navbar.tsx, src/components/ui/Container.tsx, src/pages/Main/Main.tsx, src/pages/Positioning/Positioning.tsx, src/routes/Router.tsx, src/service/map.ts
- merge 요청자: @
- 시설/도로 제보 시 지도에서 장소 선택하는 화면 구현
- 시설/도로 제보 시 지도에서 장소 선택하는 화면 구현
- Positioning 컴포넌트를 두 개의 path로 나눠 구현
=> [240613] 시설/도로 제보 시 지도에서 장소 선택하는 화면 구현

src/components/Map/Map.tsx
- merge 요청자: @
- 메인페이지의 불필요한 지도 중심 마커를 삭제함
- 메인페이지의 불필요한 지도 중심 마커를 삭제함
- Map 컴포넌트의 불필요한 상태를 삭제함
=> [240614] 메인페이지 지도 중심 마커 삭제

src/components/IsConvenient/IsConvenient.tsx, src/components/ui/Container.tsx, src/pages/WriteReview/WriteReview.tsx
- merge 요청자: @
- 리뷰 작성 페이지를 구현하여 dev에 merge 하고자 함
- IsConvenient 컴포넌트를 만듦
- 이미지 업로드는 UploadButton 컴포넌트를 사용하였음
=> [240617] 리뷰 작성 페이지 구현

src/components/MyPageForm/MyAccountRemoval.tsx, src/components/MyPageForm/MyFavoriteForm.tsx, src/components/MyPageForm/MyPageBaseForm.tsx, src/components/MyPageForm/MyProfileEditorForm.tsx, src/components/MyPageForm/MyReportForm.tsx, src/components/MyPageForm/MyReviewEditorForm.tsx, src/components/MyPageForm/MyReviewForm.tsx, src/components/Navbar/Navbar.tsx, src/pages/MyPage/MyFavorite.tsx, src/pages/MyPage/MyPageBase.tsx, src/pages/MyPage/MyProfileEditor.tsx, src/pages/MyPage/MyReport.tsx, src/pages/MyPage/MyReview.tsx, src/pages/MyPage/MyReviewEditor.tsx, src/routes/Router.tsx
- merge 요청자: @
- 마이페이지를 구현했으므로 MR 요청
- 마이페이지 기본 상태, 나의 즐겨찾기, 제보, 등록 시설, 회원 정보 조회, 회원 탈퇴 페이지 생성
=> #slope 59 make mypage

src/components/FacilityReview/ReviewFilter.tsx, src/components/FacilityReview/ReviewHeader.tsx, src/components/ui/RadioButtonGroup.tsx, src/pages/Positioning/Positioning.tsx, src/pages/PostNewFacility/PostNewFacility.tsx, src/pages/SubmitComplete/SubmitComplete.tsx, src/routes/Router.tsx
- merge 요청자: @
- 시설 등록 화면을 구현하였으므로 MR을 요청함
- 영업 시간 선택 기능 구현 예정 ( 피그마 ui대로 하려니 뇌정지 오는데, 셀렉트바로 선택한다 치면 선택 가능한 시간대가 엄청 많을텐데 30분단위로 그걸 다 넣어야하는지...?)
- 스타일 수정 예정/ 이외에 디테일한 부분 놓친거 수정할 예정
- submitComplete 페이지 header text 수정함 (틀린정보제보, 시설등록, 도로제보 다 동일하게 사용하기 위함..) 
-> 적합하지 않은 것 같으면 그냥 porps로 받아오게 바꿀 예정
=> [240622] 시설 등록 화면 구현

src/components/MyPageForm/MyPageBaseForm.tsx
- merge 요청자: @
- 마이페이지/정보수정 클릭시 비밀번호 확인 모달 높이를 수정하였으므로 mr을 요청함
- <Modal> 컴포넌트에 height값을 props으로 전달하여 수정하였음
=> [240624] 비밀번호 확인 모달 높이 수정 (#30)

src/components/RoadImageCaptioning/RoadImageCaptioning.tsx, src/components/RoadTroubleModal/RoadTroubleModal.tsx, src/components/icons/InformationIcon.tsx, src/pages/Main/Main.tsx
- 이미지 캡셔닝 ui를 구현하였음.
- api 연결 문제로 인해 아직 미완성이나, 통합테스트를 위해 MR을 요청함.
=> 240727 이미지 캡셔닝 ui 구현(#55)

src/routes/CheckAuth.tsx, src/routes/Router.tsx
- 토큰 유무에 따라 페이지 접근 권한 여부를 필터링하는 CheckAuth 컴포넌트를 작성하였으므로 MR 요청함
- 토큰 유무에 따라 페이지 접근 권한 여부를 필터링하는 CheckAuth 컴포넌트를 작성
- 관리자 페이지는 추후 수정 예정
=> [240730] 토큰 유무 필터링 컴포넌트 추가(#59)

src/components/AuthenticationForm/GetJwt.tsx, src/components/LoginButton/GoogleLoginButton.tsx, src/components/LoginButton/KakaoLoginButton.tsx, src/components/LoginButton/NaverLoginButton.tsx, src/components/MyPageForm/MyPageBaseForm.tsx, src/components/Navbar/Navbar.tsx, src/routes/CheckAuth.tsx, src/service/axiosInstance.ts, src/service/tokenUtils.js
- merge 요청자: @
- 소셜 UI 구현 (네이버, 구글, 카카오)
- Check Auth 로직 수정
- 소셜 UI 구현 (네이버, 구글, 카카오)
- Check Auth 로직 수정
=> [240804] 소셜 UI 구현 (네이버, 구글, 카카오)

src/components/MyPageForm/MyPageBaseForm.tsx, src/components/MyPageForm/MyProfileEditorForm.tsx, src/components/MyPageForm/MySocialProfileEditorForm.tsx, src/components/Navbar/Navbar.tsx, src/components/RegisterForm/RegisterIdForm.tsx, src/components/RegisterForm/RegisterSocialForm.tsx, src/pages/MyPage/MySocialProfileEditor.tsx, src/routes/Router.tsx, src/service/authUtils.js, src/service/axiosInstance.ts, src/service/tokenUtils.js
- merge 요청자: ChangHoSe
- 마이페이지 회원 정보 수정, 로그 아웃, 회원 탈퇴 로직 추가
- 마이페이지 회원 정보 수정, 로그 아웃, 회원 탈퇴 로직 추가
=> [240805] 마이페이지 로직 추가

src/components/RoadImageCaptioning/RoadImageCaptioning.tsx, src/pages/Main/Main.tsx
- 예시) 220524 프론트엔드- 회원가입 페이지의 html 파일을 추가하였음.
- 예시) 220524 백엔드- 회원가입 API를 구현하였음.
- 예시) 220527 프론트엔드 - 장바구니 추가 관련 버그를 해결하였음.
- merge 요청자: @
- 새로운 페이지를 추가하고자, html을 추가하였으므로, MR을 요청함.
- API 새로 구현하였으므로 MR을 요청함
- 상품 구매 개수를 변경해도 장바구니에 반영이 안 되었었는데, 이를 해결하였음.
- Bulma css를 이용해 디자인하였으며, 폼 작성 시 POST요청을 하도록 구현하였음
- 구현한 캡쳐 사진
- 3계층 구조를 활용하여 회원가입 API를 구현하였음.
- POSTMAN을 이용한 요청, 응답 예시 캡쳐 사진
- 수량 변경 시 장바구니에 반영이 되는 코드가 누락되어 있었는데, 이를 cart.js 파일의 40~80번째 줄에 추가하였음.
- 가능하다면, 버그, 에러 문구 등 캡쳐 -> 정상 작동 사진 캡쳐
=> Fix: 북마크 관련 로직 수정(#65)

src/components/RoadTroubleImageSlide/RoadTroubleImageSlide.tsx, src/pages/RoadReport/RoadReportForm.tsx
- 도로 제보 시 이미지 필수 업로드
- merge 요청자: @
- 길이 및 사진 업로드 개수 검사하는 로직 추가되었으므로 MR을 요청드립니다. 
- 이미지 업로드 개수에 따른 버튼 활성화 처리 
- 파일명 길 경우 alert 처리
=> fix: 도로 제보 이미지 슬라이드 에러 처리(#72)

src/components/RoadImageCaptioning/RoadImageCaptioning.tsx, src/components/RoadTroubleModal/RoadTroubleModal.tsx, src/types/roadReportDetail.ts
- 이미지 캡셔닝 기능 구현
- 이미지 캡셔닝 기능 구현
=> Feat: 이미지 캡셔닝 기능 구현

src/components/Map/Map.tsx, src/pages/Positioning/Positioning.tsx, src/pages/PostNewFacility/PostNewFacility.tsx
- 예시) 220524 프론트엔드- 회원가입 페이지의 html 파일을 추가하였음.
- 예시) 220524 백엔드- 회원가입 API를 구현하였음.
- 예시) 220527 프론트엔드 - 장바구니 추가 관련 버그를 해결하였음.
- merge 요청자: @
- 새로운 페이지를 추가하고자, html을 추가하였으므로, MR을 요청함.
- API 새로 구현하였으므로 MR을 요청함
- 상품 구매 개수를 변경해도 장바구니에 반영이 안 되었었는데, 이를 해결하였음.
- Bulma css를 이용해 디자인하였으며, 폼 작성 시 POST요청을 하도록 구현하였음
- 구현한 캡쳐 사진
- 3계층 구조를 활용하여 회원가입 API를 구현하였음.
- POSTMAN을 이용한 요청, 응답 예시 캡쳐 사진
- 수량 변경 시 장바구니에 반영이 되는 코드가 누락되어 있었는데, 이를 cart.js 파일의 40~80번째 줄에 추가하였음.
- 가능하다면, 버그, 에러 문구 등 캡쳐 -> 정상 작동 사진 캡쳐
=> Fix: 시설 등록 수정

src/components/FacilityReview/UserReview.tsx, src/components/MyPageForm/MyFavoriteForm.tsx, src/pages/UpdateNewFacility/UpdateFacility.tsx, src/pages/ViewFacilityDetails/ViewFacilityDetails.tsx, src/routes/Router.tsx
- 시설 틀린 정보 제보 구현
- 시설 틀린 정보 제보 구현
=> [240809] 시설 틀린 정보 제보 구현

src/components/FacilityMarkers/FacilityMarkers.tsx, src/components/Map/Map.tsx, src/components/RecommendedFacility/RecommendedFacility.tsx, src/components/ui/BottomSheet.tsx, src/pages/Main/Main.tsx, src/pages/RecommendFacility/RecommendFacility.tsx, src/routes/Router.tsx, src/types/facility.ts
- 예시) 220524 프론트엔드- 회원가입 페이지의 html 파일을 추가하였음.
- 예시) 220524 백엔드- 회원가입 API를 구현하였음.
- 예시) 220527 프론트엔드 - 장바구니 추가 관련 버그를 해결하였음.
- merge 요청자: @
- 새로운 페이지를 추가하고자, html을 추가하였으므로, MR을 요청함.
- API 새로 구현하였으므로 MR을 요청함
- 상품 구매 개수를 변경해도 장바구니에 반영이 안 되었었는데, 이를 해결하였음.
- Bulma css를 이용해 디자인하였으며, 폼 작성 시 POST요청을 하도록 구현하였음
- 구현한 캡쳐 사진
- 3계층 구조를 활용하여 회원가입 API를 구현하였음.
- POSTMAN을 이용한 요청, 응답 예시 캡쳐 사진
- 수량 변경 시 장바구니에 반영이 되는 코드가 누락되어 있었는데, 이를 cart.js 파일의 40~80번째 줄에 추가하였음.
- 가능하다면, 버그, 에러 문구 등 캡쳐 -> 정상 작동 사진 캡쳐
=> Feat: 장소 추천 화면 구현

src/components/AuthenticationForm/GetJwt.tsx
- JWT 교환방식 수정
- refresh token 쿠키로 access token 발급하는 방식 (소셜 로그인)
=> [240813] JWT 교환방식 수정

src/components/AuthenticationForm/GetJwt.tsx
=> Fix: ServerUrl 수정

src/components/LoginForm/LocalLoginForm.tsx
=> Fix: accessToken 헤더 수정

src/components/LoginForm/LocalLoginForm.tsx
첫 jwt 전달은 response body로 진행
첫 jwt 전달도 header로 했더니, header 수정 기능이 필요해서 로직 수정.
=> [240813] jwt 전달 방법 수정

src/components/AuthenticationForm/GetJwt.tsx
=> [240813] Social 로그인 jwt 경로 수정
